"""Reporters — render a Report into the destinations the user wants.

v0.1 ships:
  * markdown   — human-readable, GitHub-PR-comment-ready
  * json       — machine-readable
  * stdout     — pretty-print to terminal
  * file       — write either format to a path

Stubs for slack / telegram / github_pr_comment with explicit guidance.
"""
from __future__ import annotations

import json
import logging
from pathlib import Path

from rich.console import Console
from rich.markdown import Markdown

from qa_pilot.models import Finding, Report, ReportConfig, Severity, Verdict

logger = logging.getLogger("qa_pilot.reporting")

console = Console()


def render_markdown(report: Report) -> str:
    """Convert a Report into Markdown — the primary human-readable format."""
    verdict_pill = {
        Verdict.GREEN: "🟢 GREEN — ship-ready",
        Verdict.YELLOW: "🟡 YELLOW — ship with follow-up",
        Verdict.RED: "🔴 RED — blockers found",
    }[report.verdict]

    lines: list[str] = []
    lines.append(f"# QA Pilot · {verdict_pill}")
    lines.append("")
    lines.append(f"**Target:** {report.target_url}")
    lines.append(f"**Viewports:** " + ", ".join(str(v) for v in report.viewports))
    lines.append(f"**Agents run:** " + ", ".join(report.agents_run))
    lines.append(
        f"**Duration:** "
        f"{(report.finished_at - report.started_at).total_seconds():.1f}s"
    )
    lines.append(f"**Summary:** {report.summary}")
    lines.append("")

    if not report.findings:
        lines.append("No findings. Everything reviewed looked clean.")
        return "\n".join(lines)

    # Group findings by severity
    groups: dict[Severity, list[Finding]] = {s: [] for s in Severity}
    for f in report.findings:
        groups[f.severity].append(f)

    severity_order = [Severity.BLOCKER, Severity.MEDIUM, Severity.LOW, Severity.INFO]
    for sev in severity_order:
        items = groups[sev]
        if not items:
            continue
        emoji = items[0].emoji
        lines.append(f"## {emoji} {sev.value.upper()} ({len(items)})")
        lines.append("")
        for f in items:
            lines.append(f"### {emoji} {f.title}")
            lines.append(f"_via {f.agent} · id `{f.id}`_  ")
            lines.append("")
            lines.append(f.description)
            lines.append("")
            if f.repro_steps:
                lines.append("**Repro:**")
                for step in f.repro_steps:
                    lines.append(f"  - {step}")
                lines.append("")
            if f.suggested_fix:
                lines.append(f"**Suggested fix:** {f.suggested_fix}")
                lines.append("")
            if f.evidence_screenshot:
                lines.append(f"_Screenshot: `{f.evidence_screenshot}`_")
                lines.append("")
            if f.tags:
                lines.append(f"`{'` `'.join(f.tags)}`")
                lines.append("")

    lines.append("---")
    lines.append("_Generated by [qa-pilot](https://github.com/W3JDev/qa-pilot)._")
    return "\n".join(lines)


def render_json(report: Report) -> str:
    return report.model_dump_json(indent=2)


def write_to_destinations(
    report: Report,
    config: ReportConfig,
) -> list[str]:
    """Dispatch the report to each destination. Returns a list of human-readable
    'where it went' lines for logging/console output."""
    md = render_markdown(report) if "markdown" in config.formats else None
    js = render_json(report) if "json" in config.formats else None

    sent_to: list[str] = []
    for dest in config.destinations:
        try:
            if dest.type == "stdout":
                # Render with Rich — colored markdown
                if md is not None:
                    console.print(Markdown(md))
                else:
                    console.print_json(js or render_json(report))
                sent_to.append("stdout")

            elif dest.type == "file":
                if not dest.path:
                    logger.warning("file destination missing 'path' — skipping")
                    continue
                p = Path(dest.path)
                p.parent.mkdir(parents=True, exist_ok=True)
                p.write_text(md if md is not None else (js or render_json(report)), encoding="utf-8")
                sent_to.append(f"file:{p}")

            elif dest.type == "github_pr_comment":
                # Lazy-import. Requires PyGithub + GITHUB_TOKEN + GITHUB_PR_NUMBER + GITHUB_REPOSITORY
                _post_github_pr_comment(md or render_markdown(report), dest.config)
                sent_to.append("github_pr_comment")

            elif dest.type == "slack":
                _post_slack(md or render_markdown(report), dest.config)
                sent_to.append("slack")

            elif dest.type == "telegram":
                _post_telegram(md or render_markdown(report), dest.config)
                sent_to.append("telegram")
            else:
                logger.warning("unknown destination type %r", dest.type)
        except Exception as e:  # noqa: BLE001
            logger.exception("destination %s failed: %s", dest.type, e)
            sent_to.append(f"{dest.type}:ERROR ({type(e).__name__})")
    return sent_to


# -------- destination shims (lazy imports keep deps optional) ----------------


def _post_github_pr_comment(body: str, conf: dict) -> None:
    import os
    from github import Github  # type: ignore

    token = conf.get("token") or os.environ.get("GITHUB_TOKEN")
    repo_name = conf.get("repository") or os.environ.get("GITHUB_REPOSITORY")
    pr_number = int(conf.get("pr_number") or os.environ.get("GITHUB_PR_NUMBER") or 0)
    if not token or not repo_name or not pr_number:
        raise RuntimeError(
            "github_pr_comment needs GITHUB_TOKEN + GITHUB_REPOSITORY + GITHUB_PR_NUMBER"
        )
    gh = Github(token)
    repo = gh.get_repo(repo_name)
    pr = repo.get_pull(pr_number)
    pr.create_issue_comment(body)


def _post_slack(body: str, conf: dict) -> None:
    import os
    from slack_sdk.webhook import WebhookClient  # type: ignore
    url = conf.get("webhook_url") or os.environ.get("SLACK_WEBHOOK_URL")
    if not url:
        raise RuntimeError("slack destination needs webhook_url or SLACK_WEBHOOK_URL")
    WebhookClient(url).send(text=body)


def _post_telegram(body: str, conf: dict) -> None:
    import os
    import httpx
    token = conf.get("bot_token") or os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = conf.get("chat_id") or os.environ.get("TELEGRAM_CHAT_ID")
    if not token or not chat_id:
        raise RuntimeError("telegram destination needs bot_token + chat_id")
    # Telegram message limit: 4096 chars; truncate gracefully.
    msg = body[:4000] + ("\n\n…(truncated)" if len(body) > 4000 else "")
    httpx.post(
        f"https://api.telegram.org/bot{token}/sendMessage",
        json={"chat_id": chat_id, "text": msg, "parse_mode": "Markdown"},
        timeout=15.0,
    )
